### ISSUE TITLE
Building process containers may fail due to permissions

### ISSUE THREAD

**Issue by darahayes** [nearform/sudc-system#10]
If one has installed node using root privileges, (such as with apt-get) building the web process container leads to an npm error due to not having the correct permissions. This is down to the build instructions for doing a global install of bower. A quick fix for this is to globally install bower yourself before building. Having uninstalled node on my machine and reinstalled using nvm this problem was avoided, however I still think it's an issue.

The error is as follows:

``` bash
npm

ERR!
 Error: EACCES, mkdir '/home/ubuntu/.npm/connect/2.29.0'

npm

ERR!
  { [Error: EACCES, mkdir '/home/ubuntu/.npm/connect/2.29.0']

npm
 ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!
   path: '/home/ubuntu/.npm/connect/2.29.0',
npm ERR!   parent: 'startupdeathclock' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm
 ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/ubuntu/sudc-system/workspace/sudc-web
npm ERR! node -v v0.10.35

npm ERR! npm -v 1.4.28

npm ERR! path /home/ubuntu/.npm/connect/2.29.0
npm

ERR!

code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/ubuntu/.npm/connect/2.29.0'

npm

ERR!


npm

ERR!
 Additional logging details can be found in:
npm 
ERR!     /home/ubuntu/sudc-system/workspace/sudc-web/npm-debug.log
npm 
ERR! not ok code 0

npm

WARN

package.json
 web@0.1.0 No repository field.

npm

ERR!
 Error: EACCES, mkdir '/home/ubuntu/.npm/mocha/1.17.1'

npm
 ERR!  { [Error: EACCES, mkdir '/home/ubuntu/.npm/mocha/1.17.1']

npm
 ERR!   errno: 3,
npm ERR!
   code: 'EACCES',

npm

ERR!   path: '/home/ubuntu/.npm/mocha/1.17.1',
npm ERR!   parent: 'web' }
npm 
ERR! 
npm ERR! Please try running this command again as root/Administrator.


npm ERR! System
 Linux 3.13.0-44-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/ubuntu/sudc-system/workspace/sudc-web/web
npm ERR! node -v v0.10.35

npm ERR! npm -v 1.4.28

npm ERR! path /home/ubuntu/.npm/mocha/1.17.1
npm ERR! code EACCES
npm ERR! errno 3

npm 
ERR! stack Error: EACCES, mkdir '/home/ubuntu/.npm/mocha/1.17.1'

npm

ERR!


npm

ERR!
 Additional logging details can be found in:
npm ERR!     /home/ubuntu/sudc-system/workspace/sudc-web/web/npm-debug.log
npm ERR! not ok code 0

npm

ERR!
 Error: EACCES, unlink '/usr/local/bin/bower'

npm

ERR!
  { [Error: EACCES, unlink '/usr/local/bin/bower'] errno: 3, code: 'EACCES', path: '/usr/local/bin/bower' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.


npm ERR! System Linux 3.13.0-44-generic

npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bower" "-g"
npm ERR! cwd /home/ubuntu/sudc-system/workspace/sudc-web/web
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/bin/bower
npm
 ERR! code EACCES
npm ERR! errno 3

npm ERR! stack Error: EACCES, unlink '/usr/local/bin/bower'

npm

ERR!

error rolling back
 Error: EACCES, unlink '/usr/local/bin/bower'

npm
 ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/bin/bower'] errno: 3, code: 'EACCES', path: '/usr/local/bin/bower' }
npm ERR! not ok code 0
```

**Comment by mcollina** [comment]
I think that installing node with apt-get or anything else is IMHO **the worst possible thing that you can do as a node developer**. Distro package managers should not be used, mainly because you lack control of what it is going to be installed, and how. I saw horrible things with Java, Python, Ruby, Node. So, forget about distro packages.

However, _this_ is an issue. We should install `bower` without the `-g` flag and call it from `node_modules/.bin`. Can you update it @darragh-hayes?

**Comment by darahayes** [comment]
Updated. Check https://github.com/nearform/sudc-system/pull/11

**Comment by mcollina** [comment]
Fixed! :)

**Comment by darahayes** [comment]
So to conclude before I close this issue: To avoid this kind of thing you should avoid installing node using a distro package manager especially with root privileges. (I reinstalled using nvm) Otherwise you will always need to install npm modules using sudo. This might lead to problems when building process containers depending on the build instructions.

So to recap:
- Make sure node & npm are set up on your machine so you don't need to use sudo.
- Try to avoid using anything which would require root privileges in the build commands for the process container.

**Comment by mcollina** [comment]
Perfect!
Il giorno lun 2 mar 2015 alle 18:43 Darragh Hayes notifications@github.com
ha scritto:
